version: '3.8'

services:
  prometheus-instancia1:
    image: prom/prometheus:latest
    container_name: prometheus-instancia1
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring-network

  node-exporter-instancia1:
    image: prom/node-exporter:latest
    container_name: node-exporter-instancia1
    volumes:
      - /:/host:ro
    command:
      - '--path.rootfs=/host'
    ports:
      - "${NODE_EXPORTER_PORT}:9100"
    networks:
      - monitoring-network

  grafana-instancia1:
    image: grafana/grafana:latest
    container_name: grafana-instancia1
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge